apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neptune-inventory
spec:
  selector:
    matchLabels:
      service: inventory
  serviceName: "neptune-inventory"
  replicas: 1
  template:
    metadata:
      labels:
        app: neptune
        service: inventory
        name: neptune-inventory
    spec:
      containers:
      - name: arangodb
        image: arangodb:3.7.6
        env:
          - name: ARANGO_ROOT_PASSWORD
            value: root
---
apiVersion: v1
kind: Service
metadata:
  name: neptune-inventory
  labels:
    app: neptune
    service: inventory
    name: neptune-inventory
spec:
  type: NodePort
  selector:
    app: neptune
    service: inventory
    name: neptune-inventory
  ports:
  - port: 8529
    targetPort: 8529
    nodePort: 31529
    protocol: TCP
    name: http
